# vs code extension to make http requests easily


@BASE_URL=http://localhost:8001
@API_VERSION=v0
@TEAM_ID=23f8564f-3c3d-49b6-b3ef-32e219b5c25d
@IMAGE=9523db36-30f7-4c66-8236-4d7c3326872c
@ROBOT_ID=1234
@ORY_PROJECT_URL={{$dotenv %ORY_PROJECT_URL}}


# -----------------------------------------
# Auth
# -----------------------------------------

###
# @name loginStart
GET {{ORY_PROJECT_URL}}/self-service/login/api
Content-Type: application/json

@actionURL = {{loginStart.response.body.ui.action}}



###
# @name loginFinish
POST {{actionURL}}
Content-Type: application/json

{
    "identifier": "{{$dotenv %ORY_DEV_IDENTIFIER}}",
    "password": "{{$dotenv %ORY_DEV_PWD}}",
    "method": "password"
}

@SESSION_TOKEN = {{loginFinish.response.body.session_token}}




# -----------------------------------------
# Misc
# -----------------------------------------

### healthcheck
GET {{BASE_URL}}/ HTTP/1.1



# -----------------------------------------
# ADMIN
# -----------------------------------------


# -----------------------------------------
# Account
# -----------------------------------------

### Update an account
PUT {{BASE_URL}}/api/{{API_VERSION}}/admin/account HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
Content-Type: application/json

{
    "first_name": "dev",
    "last_name": "tester"
}


# -----------------------------------------
# Team
# -----------------------------------------
### create a team
POST {{BASE_URL}}/api/{{API_VERSION}}/admin/teams HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
Content-Type: application/json

{
    "name": "Test team"
}

### list teams
GET {{BASE_URL}}/api/{{API_VERSION}}/admin/teams HTTP/1.1
x-session-token: {{SESSION_TOKEN}}


### delete a team
DELETE {{BASE_URL}}/api/{{API_VERSION}}/admin/teams HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}


# -----------------------------------------
# Group
# -----------------------------------------

### list groups
GET {{BASE_URL}}/api/{{API_VERSION}}/admin/groups HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}

### create group
POST {{BASE_URL}}/api/{{API_VERSION}}/admin/groups HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}
Content-Type: application/json

{
    "name": "test group 2",
    "description": "this is a test group", 
    "robotIDs": []
}


### get group details
GET {{BASE_URL}}/api/{{API_VERSION}}/admin/groups/d30e3d38-ef40-48fc-b7e0-af2548798220 HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}
Content-Type: application/json


### update group details
PATCH {{BASE_URL}}/api/{{API_VERSION}}/admin/groups/d30e3d38-ef40-48fc-b7e0-af2548798220 HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}
Content-Type: application/json

{
    "name": "updated name",
    "description": "updated description"
}


### delete group
DELETE {{BASE_URL}}/api/{{API_VERSION}}/admin/groups/d30e3d38-ef40-48fc-b7e0-af2548798220 HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}


### get robots in a group
GET {{BASE_URL}}/api/{{API_VERSION}}/admin/groups/1ed45faa-8f7c-4d8e-a389-9f05f4ee2dd1/robots HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}
Content-Type: application/json


### add a robot to a group
POST {{BASE_URL}}/api/{{API_VERSION}}/admin/groups/1ed45faa-8f7c-4d8e-a389-9f05f4ee2dd1/robots HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}
Content-Type: application/json

{
    "robot_id": "1234"
}


### delete a robot from a group
DELETE {{BASE_URL}}/api/{{API_VERSION}}/admin/groups/1ed45faa-8f7c-4d8e-a389-9f05f4ee2dd1/robots HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}
Content-Type: application/json

{
    "robot_id": "1234"
}

# -----------------------------------------
# Provisioning
# -----------------------------------------

### create provisioning credentials
POST {{BASE_URL}}/api/{{API_VERSION}}/admin/provisioning-credentials HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}


### list provisioning credentials
GET {{BASE_URL}}/api/{{API_VERSION}}/admin/provisioning-credentials HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}


# -----------------------------------------
# Robots
# -----------------------------------------

### list robots
GET {{BASE_URL}}/api/{{API_VERSION}}/admin/robots HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}


### get a single robot
GET {{BASE_URL}}/api/{{API_VERSION}}/admin/robots/{{ROBOT_ID}} HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}

### delete a robot
DELETE {{BASE_URL}}/api/{{API_VERSION}}/admin/{{TEAM_ID}}/robots/{{ROBOT_ID}} HTTP/1.1

### delete a robot
DELETE {{BASE_URL}}/api/{{API_VERSION}}/admin/robots/{{ROBOT_ID}} HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}


### get groups a robot is in
GET {{BASE_URL}}/api/{{API_VERSION}}/admin/robots/{{ROBOT_ID}}/groups HTTP/1.1
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}


# -----------------------------------------
# Rollouts
# -----------------------------------------

### create a rollout
POST {{BASE_URL}}/api/{{API_VERSION}}/admin/rollouts HTTP/1.1
Content-Type: application/json
x-session-token: {{SESSION_TOKEN}}
air-team-id: {{TEAM_ID}}

{
    "ecu_id": "4d2406cdacd6b6c0cc89340b8995cfe5ccf7a39b970bd6fc57820a89d3a43a00",
    "image_id": "ota-ce-device-336fd3576177f3074188b444cb5c6f5147204a1f351d17b3ee87567c0ce333f9"
}



# -----------------------------------------
# Images
# -----------------------------------------


### upload an image
POST {{BASE_URL}}/api/{{API_VERSION}}/admin/{{TEAM_ID}}/images?hwids=some-hw-id,two-hwid HTTP/1.1
Content-Type: application/octet-stream

this is a sample image 4

### list images
GET {{BASE_URL}}/api/{{API_VERSION}}/admin/{{TEAM_ID}}/images HTTP/1.1



# -----------------------------------------
# DIRECTOR REPO
# -----------------------------------------

### get versioned metadata
GET {{BASE_URL}}/api/{{API_VERSION}}/director/{{TEAM_ID}}/robots/{{ROBOT_ID}}/1.targets.json HTTP/1.1




# -----------------------------------------
# IMAGE REPO
# -----------------------------------------

### get metadata
GET {{BASE_URL}}/api/{{API_VERSION}}/robot/repo/root.json HTTP/1.1
air-client-id: {{ROBOT_ID}}


### download image with image id only
GET {{BASE_URL}}/api/{{API_VERSION}}/image/{{TEAM_ID}}/images/{{IMAGE}} HTTP/1.1


### download image with sha256 and image id
GET {{BASE_URL}}/api/{{API_VERSION}}/image/{{TEAM_ID}}/images/e317b3f3501466ae189499652d5c4d2cc825444efb38c68a6e4df79f6b8beaa0.{{IMAGE}} HTTP/1.1


### download image with sha512 and image id
GET {{BASE_URL}}/api/{{API_VERSION}}/image/{{TEAM_ID}}/images/021a31d187c51c86dda1a3b4ae19e429d32452218c7dd5a145e84ea51718067bc005747b344679d86233f06134e873cc0f85e470a6282e53720eef6c8c9936f3.{{IMAGE}} HTTP/1.1





# -----------------------------------------
# TREEHUB
# -----------------------------------------

### tmp generate deltas
POST {{BASE_URL}}/api/{{API_VERSION}}/robot/treehub/{{TEAM_ID}}/deltas?from=336fd3576177f3074188b444cb5c6f5147204a1f351d17b3ee87567c0ce333f9&to=35d4b1b202668be531aae6426de6cea7541ab308f2fc5b7a8f290985da36e750 HTTP/1.1


### download delta
GET {{BASE_URL}}/api/{{API_VERSION}}/robot/treehub/deltas/M2/_TV2F38wdBiLREy1xvUUcgSh81HRez7odWfAzjM_k-NdSxsgJmi+UxquZCbebOp1Qaswjy_Ft6jykJhdo251A/superblock
air-team-id: {{TEAM_ID}}


### get ostree config
GET {{BASE_URL}}/api/{{API_VERSION}}/treehub/{{TEAM_ID}}/config HTTP/1.1


### upload a summary
PUT {{BASE_URL}}/api/{{API_VERSION}}/treehub/{{TEAM_ID}}/summary HTTP/1.1
Content-Type: application/octet-stream

this is a sample summary



### download a summary
GET {{BASE_URL}}/api/{{API_VERSION}}/robot/treehub/{{TEAM_ID}}/summary HTTP/1.1



### upload a object
PUT {{BASE_URL}}/api/{{API_VERSION}}/treehub/{{TEAM_ID}}/objects/25/1dce54d8562166b23d69dd697ee5c136691478f4ae02787c2723fb66126cfc.commit HTTP/1.1
Content-Type: application/octet-stream

this is a sample ostree object



### download a object
GET {{BASE_URL}}/api/{{API_VERSION}}/treehub/{{TEAM_ID}}/objects/24/1dce54d8562166b23d69dd697ee5c136691478f4ae02787c2723fb66126cfc.commit HTTP/1.1



### upload a ref
PUT {{BASE_URL}}/api/{{API_VERSION}}/treehub/{{TEAM_ID}}/refs/head/main HTTP/1.1
Content-Type: text/plain

251dce54d8562166b23d69dd697ee5c136691478f4ae02787c2723fb66126cfc



### get a ref
GET {{BASE_URL}}/api/{{API_VERSION}}/treehub/{{TEAM_ID}}/refs/head/main HTTP/1.1



###
GET {{BASE_URL}}/api/{{API_VERSION}}/api/v1/user_repo/targets.json HTTP/1.1