cookies:
  domain: dazzling-raman-bd5bt188g5.projects.oryapis.com
  path: /
  same_site: Strict
courier:
  smtp:
    from_name: Airbotics
  templates:
    recovery:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
    recovery_code:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
    verification:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
    verification_code:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
feature_flags:
  cacheable_sessions: false
identity:
  default_schema_id: 700927498a3ad6cf23c86c99b9ad483bed7e98d6c4eaff5b3370b6a10e714d7ce0a1b5f306ebcae5bb80418fe6e2b9c533c81059ba77e16e54c997f5351e878b
  schemas:
  - id: preset://email
    url: base64://ewogICIkaWQiOiAiaHR0cHM6Ly9zY2hlbWFzLm9yeS5zaC9wcmVzZXRzL2tyYXRvcy9pZGVudGl0eS5lbWFpbC5zY2hlbWEuanNvbiIsCiAgIiRzY2hlbWEiOiAiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEjIiwKICAidGl0bGUiOiAiUGVyc29uIiwKICAidHlwZSI6ICJvYmplY3QiLAogICJwcm9wZXJ0aWVzIjogewogICAgInRyYWl0cyI6IHsKICAgICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgImVtYWlsIjogewogICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICJmb3JtYXQiOiAiZW1haWwiLAogICAgICAgICAgInRpdGxlIjogIkUtTWFpbCIsCiAgICAgICAgICAib3J5LnNoL2tyYXRvcyI6IHsKICAgICAgICAgICAgImNyZWRlbnRpYWxzIjogewogICAgICAgICAgICAgICJwYXNzd29yZCI6IHsKICAgICAgICAgICAgICAgICJpZGVudGlmaWVyIjogdHJ1ZQogICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgIndlYmF1dGhuIjogewogICAgICAgICAgICAgICAgImlkZW50aWZpZXIiOiB0cnVlCiAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAidG90cCI6IHsKICAgICAgICAgICAgICAgICJhY2NvdW50X25hbWUiOiB0cnVlCiAgICAgICAgICAgICAgfQogICAgICAgICAgICB9LAogICAgICAgICAgICAicmVjb3ZlcnkiOiB7CiAgICAgICAgICAgICAgInZpYSI6ICJlbWFpbCIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgInZlcmlmaWNhdGlvbiI6IHsKICAgICAgICAgICAgICAidmlhIjogImVtYWlsIgogICAgICAgICAgICB9CiAgICAgICAgICB9LAogICAgICAgICAgIm1heExlbmd0aCI6IDMyMAogICAgICAgIH0KICAgICAgfSwKICAgICAgInJlcXVpcmVkIjogWwogICAgICAgICJlbWFpbCIKICAgICAgXSwKICAgICAgImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjogZmFsc2UKICAgIH0KICB9Cn0K
  - id: 76f59bd7111cdd6feb25e4d46c991e92b178c598bbda0d0ff42f6c35f4b60fef76e95d5a03297d7e32bdc4c8b61da8615d581cfa33362608d1cd63b96a65afae
    url: https://storage.googleapis.com/bac-gcs-production/76f59bd7111cdd6feb25e4d46c991e92b178c598bbda0d0ff42f6c35f4b60fef76e95d5a03297d7e32bdc4c8b61da8615d581cfa33362608d1cd63b96a65afae.json
  - id: 48bf906ee16a5a10e600b31dc401d55c0b70c9d5aa50bd04514e18a6b4ad7d2ce09d1773966976def8c7c9f80c0f89804f6b41b6511127933c72a009d6010706
    url: https://storage.googleapis.com/bac-gcs-production/48bf906ee16a5a10e600b31dc401d55c0b70c9d5aa50bd04514e18a6b4ad7d2ce09d1773966976def8c7c9f80c0f89804f6b41b6511127933c72a009d6010706.json
  - id: 302b9defb5d877bb5a79884fd286ac727ecd2b9fe0b46402d583a79f96a453719530c043292b77bc0e7dc6dff9d00989b113e2e3af7eb97566ebbdaa681cf5e6
    url: https://storage.googleapis.com/bac-gcs-production/302b9defb5d877bb5a79884fd286ac727ecd2b9fe0b46402d583a79f96a453719530c043292b77bc0e7dc6dff9d00989b113e2e3af7eb97566ebbdaa681cf5e6.json
  - id: 700927498a3ad6cf23c86c99b9ad483bed7e98d6c4eaff5b3370b6a10e714d7ce0a1b5f306ebcae5bb80418fe6e2b9c533c81059ba77e16e54c997f5351e878b
    url: https://storage.googleapis.com/bac-gcs-production/700927498a3ad6cf23c86c99b9ad483bed7e98d6c4eaff5b3370b6a10e714d7ce0a1b5f306ebcae5bb80418fe6e2b9c533c81059ba77e16e54c997f5351e878b.json
oauth2_provider: {}
selfservice:
  allowed_return_urls: []
  default_browser_return_url: /login
  flows:
    error:
      ui_url: /error
    login:
      after:
        hooks: []
        oidc:
          hooks: []
        password:
          hooks:
          - hook: require_verified_address
        webauthn:
          hooks: []
      before:
        hooks: []
      lifespan: 30m0s
      ui_url: /login
    logout:
      after: {}
    recovery:
      after:
        hooks:
        - hook: revoke_active_sessions
      before:
        hooks: []
      enabled: true
      lifespan: 30m0s
      notify_unknown_recipients: true
      ui_url: /recovery
      use: code
    registration:
      after:
        hooks: []
        oidc:
          hooks:
          - hook: session
        password:
          hooks:
          - hook: session
        webauthn:
          hooks: []
      before:
        hooks: []
      enabled: true
      lifespan: 30m0s
      ui_url: /registration
    settings:
      after:
        hooks: []
        password:
          hooks: []
        profile:
          hooks: []
      before:
        hooks: []
      lifespan: 30m0s
      privileged_session_max_age: 15m0s
      required_aal: highest_available
      ui_url: /settings
    verification:
      after:
        hooks: []
      before:
        hooks: []
      enabled: true
      lifespan: 30m0s
      notify_unknown_recipients: true
      ui_url: /verification
      use: code
  methods:
    code:
      config:
        lifespan: 15m0s
      enabled: true
    link:
      config:
        base_url: https://auth.airbotics.io/
        lifespan: 15m0s
      enabled: true
    lookup_secret:
      enabled: false
    oidc:
      config:
        providers: []
      enabled: false
    password:
      config:
        haveibeenpwned_enabled: true
        identifier_similarity_check_enabled: true
        ignore_network_errors: true
        max_breaches: 1
        min_password_length: 8
      enabled: true
    profile:
      enabled: true
    totp:
      config:
        issuer: Airbotics
      enabled: false
    webauthn:
      config:
        passwordless: false
        rp:
          display_name: Airbotics
          id: dazzling-raman-bd5bt188g5.projects.oryapis.com
          origin: https://dazzling-raman-bd5bt188g5.projects.oryapis.com
      enabled: false
serve:
  admin:
    base_url: https://dazzling-raman-bd5bt188g5.projects.oryapis.com/
    request_log:
      disable_for_health: true
  public:
    base_url: https://dazzling-raman-bd5bt188g5.projects.oryapis.com/
    cors:
      enabled: false
    request_log:
      disable_for_health: true
session:
  cookie:
    domain: dazzling-raman-bd5bt188g5.projects.oryapis.com
    name: ory_session_dazzlingramanbd5bt188g5
    path: /
    persistent: false
    same_site: Strict
  lifespan: 72h0m0s
  whoami:
    required_aal: highest_available
